/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import BLL.BLL_DatBan;
import BLL.BLL_DatBan;
import BLL.BLL_MaTenLoai;
import BLL.BLL_NhanVien;
import DTO.DTO_DatBan;
import DTO.DTO_DatBan;
import HELPER.HELPER_ChuyenDoi;
import java.sql.Array;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author CherryCe
 */
public class GUI_pnl_DatBan extends javax.swing.JPanel {
    
    int index = -1;

    /**
     * Creates new form pnl_DatBan
     */
    public GUI_pnl_DatBan() {
        initComponents();
        load();
        loadMaBan();
    }
    
    public void add() {
        DTO_DatBan datBan = new DTO_DatBan(txtMaKhachHang.getText(), txtTenKhachHang.getText(), txtSoDienThoai.getText(), String.valueOf(cboMaBan.getSelectedItem()), dateThoiGian.getDate(), rdoDathanhtoan.isSelected() ? "Đã Thanh Toán" : "Không", txtGhiChu.getText());
        if (dateThoiGian.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Dữ Liệu Không Được Để Trống !!!");
            return;
        }
        if (txtSoDienThoai.getText().length() > 10) {
            JOptionPane.showMessageDialog(this, "Lỗi Định Dạng Số ???");
            return;
        } else {
            BLL_DatBan.add(datBan);
        }
    }
    
    public void delete(int index) {
        if (index < 0) {
            JOptionPane.showMessageDialog(this, "Bạn Chưa Chọn Dòng Cần Sửa");
        } else {
            int choice = JOptionPane.showConfirmDialog(this, "Bạn Có Muốn Xóa Không ?", "Xóa", JOptionPane.YES_NO_OPTION);
            if (choice == JOptionPane.YES_OPTION) {
                int indexs[] = tblDatBan.getSelectedRows();
                for (int i = 0; i < indexs.length; i++) {
                    String maKhachHang = tblDatBan.getValueAt(indexs[i], 0).toString();
                    BLL_DatBan.delete(maKhachHang);
                }
            }
            return;
        }
    }
    
    public void edit(int index) {
        if (index < 0) {
            JOptionPane.showMessageDialog(this, "Bạn Chưa Chọn Dòng Cần Sửa");
        }
        DTO_DatBan datBan = new DTO_DatBan(txtMaKhachHang.getText(), txtTenKhachHang.getText(), txtSoDienThoai.getText(), String.valueOf(cboMaBan.getSelectedItem()), dateThoiGian.getDate(), rdoDathanhtoan.isSelected() ? "Đã Thanh Toán" : "Không", txtGhiChu.getText());
        BLL_DatBan.edit(datBan);
    }
    
    public void reset() {
        txtMaKhachHang.setText(null);
        txtTenKhachHang.setText(null);
        txtSoDienThoai.setText(null);
        cboMaBan.setSelectedItem(null);
        dateThoiGian.setDate(null);
        rdoKhong.setSelected(true);
        txtGhiChu.setText(null);
    }
    
    public void fill(int index) {
        txtMaKhachHang.setText(tblDatBan.getValueAt(index, 0).toString());
        txtTenKhachHang.setText(tblDatBan.getValueAt(index, 1).toString());
        txtSoDienThoai.setText(tblDatBan.getValueAt(index, 2).toString());
        cboMaBan.setSelectedItem(tblDatBan.getValueAt(index, 3));
        dateThoiGian.setDate(HELPER_ChuyenDoi.LayNgayDate(tblDatBan.getValueAt(index, 4).toString()));
        String traTruoc = tblDatBan.getValueAt(index, 5).toString();
        if (traTruoc.equals("Đã Thanh Toán")) {
            rdoDathanhtoan.setSelected(true);
        } else if (traTruoc.equals("Không")) {
            rdoKhong.setSelected(true);
        }
        txtGhiChu.setText(tblDatBan.getValueAt(index, 6).toString());
    }
    
    public void load() {
        ArrayList<DTO_DatBan> array = BLL_DatBan.select();
        BLL_DatBan.load(array, tblDatBan);
        rdoKhong.setSelected(true);
    }
    
    public void loadMaBan() {
        ArrayList<DTO_DatBan> array = BLL_DatBan.selectMaBan();
        BLL_DatBan.loadMaBan(array, cboMaBan);
    }
    
    public void exit() {
        int choice = JOptionPane.showConfirmDialog(this, "Bạn Có Muốn Thoát Chương Trình ?", "Thoát", JOptionPane.YES_NO_OPTION);
        if (choice == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
        return;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grpTraTruoc = new javax.swing.ButtonGroup();
        pnlDatBan = new javax.swing.JPanel();
        lblThoat = new javax.swing.JLabel();
        scrDatBan = new javax.swing.JScrollPane();
        tblDatBan = new javax.swing.JTable();
        pnlFormChinh = new javax.swing.JPanel();
        lblSoDienThoai = new javax.swing.JLabel();
        lblTenKhachHang = new javax.swing.JLabel();
        lblMaBan = new javax.swing.JLabel();
        lblNgayDat = new javax.swing.JLabel();
        lblTraTruoc = new javax.swing.JLabel();
        pnlGhiChu = new javax.swing.JPanel();
        txtGhiChu = new javax.swing.JTextField();
        txtTenKhachHang = new javax.swing.JTextField();
        txtSoDienThoai = new javax.swing.JTextField();
        cboMaBan = new javax.swing.JComboBox<>();
        rdoKhong = new javax.swing.JRadioButton();
        rdoDathanhtoan = new javax.swing.JRadioButton();
        btnLamMoi = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        dateThoiGian = new com.toedter.calendar.JDateChooser();
        lblMaKhachHang = new javax.swing.JLabel();
        txtMaKhachHang = new javax.swing.JTextField();
        lblTieuDe = new javax.swing.JLabel();
        lblThongTin = new javax.swing.JLabel();

        pnlDatBan.setBackground(new java.awt.Color(255, 255, 255));
        pnlDatBan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblThoat.setBackground(new java.awt.Color(49, 139, 130));
        lblThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Close_18px.png"))); // NOI18N
        lblThoat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblThoatMouseClicked(evt);
            }
        });
        pnlDatBan.add(lblThoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 10, 20, 20));

        tblDatBan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã Khách Hàng", "Tên Khách Hàng", "Số Điện Thoại", "Mã Bàn", "Ngày Đặt", "Trả Trước", "Ghi Chú"
            }
        ));
        tblDatBan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDatBanMouseClicked(evt);
            }
        });
        scrDatBan.setViewportView(tblDatBan);

        pnlDatBan.add(scrDatBan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 850, 260));

        pnlFormChinh.setBackground(new java.awt.Color(255, 255, 255));
        pnlFormChinh.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSoDienThoai.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblSoDienThoai.setForeground(new java.awt.Color(49, 139, 130));
        lblSoDienThoai.setText("Số Điện Thoại:");
        pnlFormChinh.add(lblSoDienThoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 113, -1, -1));

        lblTenKhachHang.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblTenKhachHang.setForeground(new java.awt.Color(49, 139, 130));
        lblTenKhachHang.setText("Tên Khách Hàng:");
        pnlFormChinh.add(lblTenKhachHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 79, -1, -1));

        lblMaBan.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblMaBan.setForeground(new java.awt.Color(49, 139, 130));
        lblMaBan.setText("Mã Bàn:");
        pnlFormChinh.add(lblMaBan, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 147, -1, -1));

        lblNgayDat.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblNgayDat.setForeground(new java.awt.Color(49, 139, 130));
        lblNgayDat.setText("Ngày Đặt:");
        pnlFormChinh.add(lblNgayDat, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 179, 90, 29));

        lblTraTruoc.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblTraTruoc.setForeground(new java.awt.Color(49, 139, 130));
        lblTraTruoc.setText("Trả Trước");
        pnlFormChinh.add(lblTraTruoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 221, -1, -1));

        pnlGhiChu.setBackground(new java.awt.Color(255, 255, 255));
        pnlGhiChu.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ghi chú", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 13), new java.awt.Color(49, 139, 130))); // NOI18N
        pnlGhiChu.setForeground(new java.awt.Color(49, 139, 130));
        pnlGhiChu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtGhiChu.setBorder(null);
        txtGhiChu.setPreferredSize(new java.awt.Dimension(64, 14));
        txtGhiChu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGhiChuActionPerformed(evt);
            }
        });
        pnlGhiChu.add(txtGhiChu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 330, 30));

        pnlFormChinh.add(pnlGhiChu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 350, 62));
        pnlGhiChu.getAccessibleContext().setAccessibleName("Ghi Chú");

        pnlFormChinh.add(txtTenKhachHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 77, 220, -1));

        txtSoDienThoai.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSoDienThoaiKeyReleased(evt);
            }
        });
        pnlFormChinh.add(txtSoDienThoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 111, 220, -1));

        cboMaBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboMaBanActionPerformed(evt);
            }
        });
        pnlFormChinh.add(cboMaBan, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 145, 220, -1));

        rdoKhong.setBackground(new java.awt.Color(255, 255, 255));
        grpTraTruoc.add(rdoKhong);
        rdoKhong.setForeground(new java.awt.Color(49, 139, 130));
        rdoKhong.setText("Không");
        pnlFormChinh.add(rdoKhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 220, -1, -1));

        rdoDathanhtoan.setBackground(new java.awt.Color(255, 255, 255));
        grpTraTruoc.add(rdoDathanhtoan);
        rdoDathanhtoan.setForeground(new java.awt.Color(49, 139, 130));
        rdoDathanhtoan.setText("Đã Thanh Toán");
        pnlFormChinh.add(rdoDathanhtoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 220, -1, -1));

        btnLamMoi.setForeground(new java.awt.Color(49, 139, 130));
        btnLamMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/reset_28px.png"))); // NOI18N
        btnLamMoi.setText("Làm Mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });
        pnlFormChinh.add(btnLamMoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 270, 110, -1));

        btnThem.setForeground(new java.awt.Color(49, 139, 130));
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/add_28px.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        pnlFormChinh.add(btnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 270, 100, -1));

        btnXoa.setForeground(new java.awt.Color(49, 139, 130));
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Delete_28px.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        pnlFormChinh.add(btnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 270, -1, -1));

        btnSua.setForeground(new java.awt.Color(49, 139, 130));
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/edit_28px.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.setToolTipText("");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        pnlFormChinh.add(btnSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 270, 90, -1));

        dateThoiGian.setDateFormatString("dd-MM-yyyy");
        pnlFormChinh.add(dateThoiGian, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 218, -1));

        lblMaKhachHang.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblMaKhachHang.setForeground(new java.awt.Color(49, 139, 130));
        lblMaKhachHang.setText("Mã Khách Hàng:");
        pnlFormChinh.add(lblMaKhachHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 45, -1, -1));

        txtMaKhachHang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMaKhachHangKeyReleased(evt);
            }
        });
        pnlFormChinh.add(txtMaKhachHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 43, 220, -1));

        lblTieuDe.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        lblTieuDe.setForeground(new java.awt.Color(49, 139, 130));
        lblTieuDe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTieuDe.setText("ĐẶT BÀN");
        lblTieuDe.setToolTipText("");
        pnlFormChinh.add(lblTieuDe, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, 290, -1));

        lblThongTin.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblThongTin.setForeground(new java.awt.Color(49, 139, 130));
        lblThongTin.setText("Thông Tin:");
        pnlFormChinh.add(lblThongTin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 842, -1));

        pnlDatBan.add(pnlFormChinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 900, 320));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pnlDatBan, javax.swing.GroupLayout.PREFERRED_SIZE, 920, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pnlDatBan, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lblThoatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThoatMouseClicked
        exit();
    }//GEN-LAST:event_lblThoatMouseClicked

    private void tblDatBanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDatBanMouseClicked
        index = tblDatBan.getSelectedRow();
        fill(index);
    }//GEN-LAST:event_tblDatBanMouseClicked

    private void cboMaBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboMaBanActionPerformed

    }//GEN-LAST:event_cboMaBanActionPerformed

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        reset();
        load();
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        add();
        load();
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        index = tblDatBan.getSelectedRow();
        delete(index);
        reset();
        load();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        index = tblDatBan.getSelectedRow();
        edit(index);
        load();
    }//GEN-LAST:event_btnSuaActionPerformed

    private void txtGhiChuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGhiChuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGhiChuActionPerformed

    private void txtSoDienThoaiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSoDienThoaiKeyReleased
        txtSoDienThoai.setText(txtSoDienThoai.getText().replaceAll("[abcdefghijklmnopqrstuvwxyz-]", ""));
    }//GEN-LAST:event_txtSoDienThoaiKeyReleased

    private void txtMaKhachHangKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMaKhachHangKeyReleased
      BLL_MaTenLoai.isAdd(tblDatBan, txtMaKhachHang, btnThem, 0);
    }//GEN-LAST:event_txtMaKhachHangKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cboMaBan;
    private com.toedter.calendar.JDateChooser dateThoiGian;
    private javax.swing.ButtonGroup grpTraTruoc;
    private javax.swing.JLabel lblMaBan;
    private javax.swing.JLabel lblMaKhachHang;
    private javax.swing.JLabel lblNgayDat;
    private javax.swing.JLabel lblSoDienThoai;
    private javax.swing.JLabel lblTenKhachHang;
    private javax.swing.JLabel lblThoat;
    private javax.swing.JLabel lblThongTin;
    private javax.swing.JLabel lblTieuDe;
    private javax.swing.JLabel lblTraTruoc;
    private javax.swing.JPanel pnlDatBan;
    private javax.swing.JPanel pnlFormChinh;
    private javax.swing.JPanel pnlGhiChu;
    private javax.swing.JRadioButton rdoDathanhtoan;
    private javax.swing.JRadioButton rdoKhong;
    private javax.swing.JScrollPane scrDatBan;
    private javax.swing.JTable tblDatBan;
    private javax.swing.JTextField txtGhiChu;
    private javax.swing.JTextField txtMaKhachHang;
    private javax.swing.JTextField txtSoDienThoai;
    private javax.swing.JTextField txtTenKhachHang;
    // End of variables declaration//GEN-END:variables
}
