/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import BLL.BLL_MaTenLoai;
import BLL.BLL_TaiKhoan;
import DAL.DAL_TaiKhoan;
import DTO.DTO_TaiKhoan;
import java.awt.event.KeyEvent;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author CherryCe
 */
public class GUI_frm_DangNhap extends javax.swing.JFrame {
    
    boolean isPassword = false;
    public static String taiKhoan = null;

    /**
     * Creates new form frm_TaiKhoan
     */
    public GUI_frm_DangNhap() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    public void loading() {
        GUI_dal_Loading loading = new GUI_dal_Loading(this, true);
        loading.setVisible(true);
    }
    
    public void login() {
        String tenDangNhap = txtTaiKhoan.getText();
        String matKhau = String.valueOf(txtMatKhau.getPassword());
        if (tenDangNhap.isEmpty() || matKhau.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Tài Khoản Hoặc Mật Khẩu Không Được Để Trống");
        } else {
            try {
                if (BLL_TaiKhoan.select(tenDangNhap, matKhau).isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Tài Khoản Hoặc Mật Khẩu Không Đúng");
                } else {
                    JOptionPane.showMessageDialog(this, "Đăng Nhập Thành Công");
                    taiKhoan = txtTaiKhoan.getText();
                    this.setVisible(false);
                    new GUI_frm_TrangChu().setVisible(true);
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }
    
    public void isPassword() {
        if (!isPassword) {
            txtMatKhau.setEchoChar((char) 0);
            isPassword = true;
            lblIconIsPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Eye-Visible-icon.png")));
            
        } else {
            txtMatKhau.setEchoChar('*');
            isPassword = false;
            lblIconIsPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Eye-Blind-icon.png")));
        }
    }
    
    public static void isPhanQuyen(JButton Them, JButton Xoa, JButton Sua) {
        if (BLL_MaTenLoai.getPhanQuyen(GUI_frm_DangNhap.taiKhoan).equals("Quản Lý")) {
            Them.setEnabled(true);
            Xoa.setEnabled(true);
            Sua.setEnabled(true);
        } else if (BLL_MaTenLoai.getPhanQuyen(GUI_frm_DangNhap.taiKhoan).equals("Nhân Viên")) {
            Them.setEnabled(false);
            Xoa.setEnabled(false);
            Sua.setEnabled(false);
        }
    }
    
    public void exit() {
        int choice = JOptionPane.showConfirmDialog(this, "Bạn Có Muốn Thoát Chương Trình ?", "Thoát", JOptionPane.YES_NO_OPTION);
        if (choice == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
        return;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHinhAnh = new javax.swing.JLabel();
        lblTaiKhoan = new javax.swing.JLabel();
        lblKiemTraTaiKhoan = new javax.swing.JLabel();
        pnlDangNhap = new javax.swing.JPanel();
        lblIconTaiKhoan = new javax.swing.JLabel();
        lblIconMatKhau = new javax.swing.JLabel();
        btnDangNhap = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        txtTaiKhoan = new javax.swing.JTextField();
        lblDangNhap = new javax.swing.JLabel();
        lblIconIsPassword = new javax.swing.JLabel();
        txtMatKhau = new javax.swing.JPasswordField();
        lblThoat = new javax.swing.JLabel();
        chkMatKhau = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(654, 410));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(654, 410));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHinhAnh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/bg-306x410.jpg"))); // NOI18N
        getContentPane().add(lblHinhAnh, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 304, -1));

        lblTaiKhoan.setBackground(new java.awt.Color(255, 255, 255));
        lblTaiKhoan.setText("ĐĂNG KÍ");
        lblTaiKhoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTaiKhoanMouseClicked(evt);
            }
        });
        getContentPane().add(lblTaiKhoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 380, -1, 30));

        lblKiemTraTaiKhoan.setText("Bạn Chưa Có Tài Khoản ?");
        getContentPane().add(lblKiemTraTaiKhoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 380, -1, 30));

        pnlDangNhap.setBackground(new java.awt.Color(255, 255, 255));
        pnlDangNhap.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIconTaiKhoan.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblIconTaiKhoan.setForeground(new java.awt.Color(49, 139, 130));
        lblIconTaiKhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/accountt_28px.png"))); // NOI18N
        lblIconTaiKhoan.setToolTipText("");
        pnlDangNhap.add(lblIconTaiKhoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 145, -1, -1));

        lblIconMatKhau.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblIconMatKhau.setForeground(new java.awt.Color(49, 139, 130));
        lblIconMatKhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/password_28px.png"))); // NOI18N
        pnlDangNhap.add(lblIconMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 26, 22));

        btnDangNhap.setBackground(new java.awt.Color(49, 139, 130));
        btnDangNhap.setForeground(new java.awt.Color(51, 51, 51));
        btnDangNhap.setText("Đăng Nhập");
        btnDangNhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDangNhapMouseClicked(evt);
            }
        });
        btnDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangNhapActionPerformed(evt);
            }
        });
        pnlDangNhap.add(btnDangNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 294, -1, 35));

        btnThoat.setBackground(new java.awt.Color(49, 139, 130));
        btnThoat.setForeground(new java.awt.Color(51, 51, 51));
        btnThoat.setText("Thoát");
        btnThoat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThoatMouseClicked(evt);
            }
        });
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });
        pnlDangNhap.add(btnThoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 294, 88, 35));
        pnlDangNhap.add(txtTaiKhoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 142, 210, 30));

        lblDangNhap.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblDangNhap.setForeground(new java.awt.Color(49, 139, 130));
        lblDangNhap.setText("ĐĂNG NHẬP");
        pnlDangNhap.add(lblDangNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 57, -1, 54));

        lblIconIsPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Eye-Blind-icon.png"))); // NOI18N
        lblIconIsPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblIconIsPasswordMouseClicked(evt);
            }
        });
        pnlDangNhap.add(lblIconIsPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 196, -1, -1));

        txtMatKhau.setFocusAccelerator('\u0001');
        txtMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMatKhauActionPerformed(evt);
            }
        });
        txtMatKhau.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMatKhauKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMatKhauKeyReleased(evt);
            }
        });
        pnlDangNhap.add(txtMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 192, 210, 30));

        lblThoat.setBackground(new java.awt.Color(49, 139, 130));
        lblThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Close_18px.png"))); // NOI18N
        lblThoat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblThoatMouseClicked(evt);
            }
        });
        pnlDangNhap.add(lblThoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, -1, -1));

        chkMatKhau.setBackground(new java.awt.Color(255, 255, 255));
        chkMatKhau.setText("Ghi Nhớ Mật Khẩu");
        chkMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkMatKhauActionPerformed(evt);
            }
        });
        pnlDangNhap.add(chkMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, -1, 30));

        getContentPane().add(pnlDangNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, -1, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblTaiKhoanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTaiKhoanMouseClicked
        this.setVisible(false);
        new GUI_frm_DangKi().setVisible(true);
    }//GEN-LAST:event_lblTaiKhoanMouseClicked

    private void btnDangNhapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDangNhapMouseClicked

    }//GEN-LAST:event_btnDangNhapMouseClicked

    private void btnDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangNhapActionPerformed
        login();
    }//GEN-LAST:event_btnDangNhapActionPerformed

    private void btnThoatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThoatMouseClicked

    }//GEN-LAST:event_btnThoatMouseClicked

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        exit();
    }//GEN-LAST:event_btnThoatActionPerformed

    private void lblIconIsPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconIsPasswordMouseClicked
        isPassword();
    }//GEN-LAST:event_lblIconIsPasswordMouseClicked

    private void txtMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMatKhauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMatKhauActionPerformed

    private void txtMatKhauKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMatKhauKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            login();
        }
    }//GEN-LAST:event_txtMatKhauKeyPressed

    private void txtMatKhauKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMatKhauKeyReleased

    }//GEN-LAST:event_txtMatKhauKeyReleased

    private void lblThoatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThoatMouseClicked
        exit();
    }//GEN-LAST:event_lblThoatMouseClicked

    private void chkMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkMatKhauActionPerformed

    }//GEN-LAST:event_chkMatKhauActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_frm_DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_frm_DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_frm_DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_frm_DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_frm_DangNhap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangNhap;
    private javax.swing.JButton btnThoat;
    private javax.swing.JCheckBox chkMatKhau;
    private javax.swing.JLabel lblDangNhap;
    private javax.swing.JLabel lblHinhAnh;
    private javax.swing.JLabel lblIconIsPassword;
    private javax.swing.JLabel lblIconMatKhau;
    private javax.swing.JLabel lblIconTaiKhoan;
    public javax.swing.JLabel lblKiemTraTaiKhoan;
    public javax.swing.JLabel lblTaiKhoan;
    private javax.swing.JLabel lblThoat;
    private javax.swing.JPanel pnlDangNhap;
    private javax.swing.JPasswordField txtMatKhau;
    private javax.swing.JTextField txtTaiKhoan;
    // End of variables declaration//GEN-END:variables
}
