/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import BLL.BLL_MaTenLoai;
import BLL.BLL_TaiKhoan;
import DTO.DTO_TaiKhoan;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author CherryCe
 */
public class GUI_pnl_TaiKhoan extends javax.swing.JPanel {

    int index = -1;

    /**
     * Creates new form pnl_DanhSach
     */
    public GUI_pnl_TaiKhoan() {
        initComponents();
        load();
    }

    public void add() {
        DTO_TaiKhoan taiKhoan = new DTO_TaiKhoan(txtMaNhanVien.getText(), txtTaiKhoan.getText(), txtMatKhau.getText(), String.valueOf(cboPhanQuyen.getSelectedItem()));
        BLL_TaiKhoan.add(taiKhoan);
    }

    public void delete(int index) {
        if (index < 0) {
            JOptionPane.showMessageDialog(this, "Bạn Chưa Chọn Dòng Cần Sửa");
        }
        int choice = JOptionPane.showConfirmDialog(this, "Bạn Có Muốn Xóa Không ?", "Xóa", JOptionPane.YES_NO_OPTION);
        if (choice == JOptionPane.YES_OPTION) {
            int indexs[] = tblTaiKhoan.getSelectedRows();
            for (int i = 0; i < indexs.length; i++) {
                String maNhanVien = tblTaiKhoan.getValueAt(indexs[i], 0).toString();
                BLL_TaiKhoan.delete(maNhanVien);
            }
            DTO_TaiKhoan taiKhoan = new DTO_TaiKhoan(txtMaNhanVien.getText(), txtTaiKhoan.getText(), txtMatKhau.getText(), String.valueOf(cboPhanQuyen.getSelectedItem()));
        }
        return;
    }

    public void edit(int index) {
        if (index < 0) {
            JOptionPane.showMessageDialog(this, "Bạn Chưa Chọn Dòng Cần Sửa");
        }
        DTO_TaiKhoan taiKhoan = new DTO_TaiKhoan(txtMaNhanVien.getText(), txtTaiKhoan.getText(), txtMatKhau.getText(), String.valueOf(cboPhanQuyen.getSelectedItem()));
        BLL_TaiKhoan.edit(taiKhoan);
    }

    public void search() {
        if (txtTimKiem.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Tìm Kiếm Không Được Để Trống");
        } else {
            ArrayList<DTO_TaiKhoan> array = BLL_TaiKhoan.search(txtTimKiem.getText());
            BLL_TaiKhoan.load(array, tblTaiKhoan);
        }
    }

    public void reset() {
        txtMaNhanVien.setText(null);
        txtTaiKhoan.setText(null);
        txtMatKhau.setText(null);
        cboPhanQuyen.setSelectedItem(null);
        txtTimKiem.setText(null);
    }

    public void fill(int index) {
        txtMaNhanVien.setText(tblTaiKhoan.getValueAt(index, 0).toString());
        txtTaiKhoan.setText(tblTaiKhoan.getValueAt(index, 1).toString());
        txtMatKhau.setText(tblTaiKhoan.getValueAt(index, 2).toString());
        cboPhanQuyen.setSelectedItem(tblTaiKhoan.getValueAt(index, 3).toString());
    }

    public void load() {
        ArrayList<DTO_TaiKhoan> array = BLL_TaiKhoan.select();
        BLL_TaiKhoan.load(array, tblTaiKhoan);
    }

    public void exit() {
        int choice = JOptionPane.showConfirmDialog(this, "Bạn Có Muốn Thoát Chương Trình ?", "Thoát", JOptionPane.YES_NO_OPTION);
        if (choice == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
        return;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTaiKhoan = new javax.swing.JPanel();
        scrTaiKhoan = new javax.swing.JScrollPane();
        tblTaiKhoan = new javax.swing.JTable();
        pnlFormChinh = new javax.swing.JPanel();
        lblMatKhau = new javax.swing.JLabel();
        lblTaiKhoan = new javax.swing.JLabel();
        txtTaiKhoan = new javax.swing.JTextField();
        txtMatKhau = new javax.swing.JTextField();
        btnLamMoi = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        lblThongTin = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        lblPhanQuyen = new javax.swing.JLabel();
        cboPhanQuyen = new javax.swing.JComboBox<>();
        lblMaNhanVien = new javax.swing.JLabel();
        txtMaNhanVien = new javax.swing.JTextField();
        pnlTieuDe = new javax.swing.JPanel();
        lblTieuDe = new javax.swing.JLabel();
        lblThoat = new javax.swing.JLabel();

        pnlTaiKhoan.setBackground(new java.awt.Color(255, 255, 255));
        pnlTaiKhoan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblTaiKhoan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã Nhân Viên", "Tên Ðăng Nhập", "Mật Khẩu", "Phân Quyền"
            }
        ));
        tblTaiKhoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTaiKhoanMouseClicked(evt);
            }
        });
        scrTaiKhoan.setViewportView(tblTaiKhoan);

        pnlTaiKhoan.add(scrTaiKhoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 127, 560, 480));

        pnlFormChinh.setBackground(new java.awt.Color(255, 255, 255));
        pnlFormChinh.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMatKhau.setForeground(new java.awt.Color(49, 139, 130));
        lblMatKhau.setText("Mật Khẩu:");
        pnlFormChinh.add(lblMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 65, 30));

        lblTaiKhoan.setForeground(new java.awt.Color(49, 139, 130));
        lblTaiKhoan.setText("Tài Khoản:");
        pnlFormChinh.add(lblTaiKhoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 65, 30));

        txtTaiKhoan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTaiKhoanKeyReleased(evt);
            }
        });
        pnlFormChinh.add(txtTaiKhoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 180, 30));
        pnlFormChinh.add(txtMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 180, 30));

        btnLamMoi.setForeground(new java.awt.Color(49, 139, 130));
        btnLamMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/reset_28px.png"))); // NOI18N
        btnLamMoi.setText("Làm Mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });
        pnlFormChinh.add(btnLamMoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 330, 110, -1));

        btnXoa.setForeground(new java.awt.Color(49, 139, 130));
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Delete_28px.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        pnlFormChinh.add(btnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 400, 110, -1));

        btnSua.setForeground(new java.awt.Color(49, 139, 130));
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/edit_28px.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.setToolTipText("");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        pnlFormChinh.add(btnSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 400, 110, -1));

        btnThem.setForeground(new java.awt.Color(49, 139, 130));
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/add_28px.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        pnlFormChinh.add(btnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 330, 110, -1));

        lblThongTin.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblThongTin.setForeground(new java.awt.Color(49, 139, 130));
        lblThongTin.setText("Thông Tin:");
        lblThongTin.setToolTipText("");
        pnlFormChinh.add(lblThongTin, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, 20));

        txtTimKiem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTimKiem.setForeground(new java.awt.Color(49, 139, 130));
        txtTimKiem.setToolTipText("");
        txtTimKiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimKiemKeyReleased(evt);
            }
        });
        pnlFormChinh.add(txtTimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 190, -1));

        btnTimKiem.setForeground(new java.awt.Color(49, 139, 130));
        btnTimKiem.setText("Tìm Kiếm");
        btnTimKiem.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnTimKiem.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });
        pnlFormChinh.add(btnTimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 1, -1, -1));

        lblPhanQuyen.setForeground(new java.awt.Color(49, 139, 130));
        lblPhanQuyen.setText("Phân Quyền:");
        pnlFormChinh.add(lblPhanQuyen, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, 30));

        cboPhanQuyen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Quản Lý", "Nhân Viên" }));
        pnlFormChinh.add(cboPhanQuyen, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 180, 30));

        lblMaNhanVien.setForeground(new java.awt.Color(49, 139, 130));
        lblMaNhanVien.setText("Mã Nhân Viên:");
        pnlFormChinh.add(lblMaNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 80, 30));

        txtMaNhanVien.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMaNhanVienKeyReleased(evt);
            }
        });
        pnlFormChinh.add(txtMaNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 180, 30));

        pnlTaiKhoan.add(pnlFormChinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 100, 340, 500));

        pnlTieuDe.setBackground(new java.awt.Color(255, 255, 255));
        pnlTieuDe.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTieuDe.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lblTieuDe.setForeground(new java.awt.Color(49, 139, 130));
        lblTieuDe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTieuDe.setText("QUẢN LÝ TÀI KHOẢN");
        pnlTieuDe.add(lblTieuDe, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 21, 550, -1));

        lblThoat.setBackground(new java.awt.Color(49, 139, 130));
        lblThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Close_18px.png"))); // NOI18N
        lblThoat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblThoatMouseClicked(evt);
            }
        });
        pnlTieuDe.add(lblThoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 10, -1, -1));

        pnlTaiKhoan.add(pnlTieuDe, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 90));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 920, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblTaiKhoanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTaiKhoanMouseClicked
        index = tblTaiKhoan.getSelectedRow();
        fill(index);
    }//GEN-LAST:event_tblTaiKhoanMouseClicked

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        add();
        load();
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        index = tblTaiKhoan.getSelectedRow();
        edit(index);
        load();
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        index = tblTaiKhoan.getSelectedRow();
        delete(index);
        reset();
        load();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        reset();
        load();
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void txtTimKiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemKeyReleased

    }//GEN-LAST:event_txtTimKiemKeyReleased

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        search();
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void lblThoatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThoatMouseClicked
        exit();
    }//GEN-LAST:event_lblThoatMouseClicked

    private void txtMaNhanVienKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMaNhanVienKeyReleased
       BLL_MaTenLoai.isAdd(tblTaiKhoan, txtMaNhanVien, btnThem, 0);
    }//GEN-LAST:event_txtMaNhanVienKeyReleased

    private void txtTaiKhoanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTaiKhoanKeyReleased
        BLL_MaTenLoai.isAdd(tblTaiKhoan, txtTaiKhoan, btnThem, 1);
    }//GEN-LAST:event_txtTaiKhoanKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cboPhanQuyen;
    private javax.swing.JLabel lblMaNhanVien;
    private javax.swing.JLabel lblMatKhau;
    private javax.swing.JLabel lblPhanQuyen;
    private javax.swing.JLabel lblTaiKhoan;
    private javax.swing.JLabel lblThoat;
    private javax.swing.JLabel lblThongTin;
    private javax.swing.JLabel lblTieuDe;
    private javax.swing.JPanel pnlFormChinh;
    private javax.swing.JPanel pnlTaiKhoan;
    private javax.swing.JPanel pnlTieuDe;
    private javax.swing.JScrollPane scrTaiKhoan;
    private javax.swing.JTable tblTaiKhoan;
    private javax.swing.JTextField txtMaNhanVien;
    private javax.swing.JTextField txtMatKhau;
    private javax.swing.JTextField txtTaiKhoan;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
