/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import javax.swing.JOptionPane;

/**
 *
 * @author CherryCe
 */
public class GUI_frm_TrangChu extends javax.swing.JFrame {

    /**
     * Creates new form frm_TrangChu
     */
    public GUI_frm_TrangChu() {
        initComponents();
        setLocationRelativeTo(null);
    }

    public void thoat() {
        int choice = JOptionPane.showConfirmDialog(this, "Bạn có muốn thoát chương trình ?", "Thoát", JOptionPane.YES_NO_OPTION);
        if (choice == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
        return;
    }

    public void menuMonAn() {
        this.setVisible(false);
//        new GUI_dal_Loading(this, true).setVisible(true);
        GUI_frm_Menu menu = new GUI_frm_Menu();
        menu.setVisible(true);
        menu.menuMonAn();
    }

    public void menuDatBan() {
        this.setVisible(false);
//        new GUI_dal_Loading(this, true).setVisible(true);
        GUI_frm_Menu menu = new GUI_frm_Menu();
        menu.setVisible(true);
        menu.menuDatBan();
    }

    public void menuHoaDon() {
        this.setVisible(false);
//        new GUI_dal_Loading(this, true).setVisible(true);
        GUI_frm_Menu menu = new GUI_frm_Menu();
        menu.setVisible(true);
        menu.menuHoaDon();
    }
    
    public void menuThongKe() {
        this.setVisible(false);
//        new GUI_dal_Loading(this, true).setVisible(true);
        GUI_frm_Menu menu = new GUI_frm_Menu();
        menu.setVisible(true);
        menu.menuThongKe();
    }
    
    public void menuNhanVien() {
        this.setVisible(false);
//        new GUI_dal_Loading(this, true).setVisible(true);
        GUI_frm_Menu menu = new GUI_frm_Menu();
        menu.setVisible(true);
        menu.menuNhanVien();
    }
    
    public void menuDanhSach() {
        this.setVisible(false);
//        new GUI_dal_Loading(this, true).setVisible(true);
        GUI_frm_Menu menu = new GUI_frm_Menu();
        menu.setVisible(true);
        menu.menuDanhSach();
    }
    
    public void menuTaiKhoan() {
        this.setVisible(false);
//        new GUI_dal_Loading(this, true).setVisible(true);
        GUI_frm_Menu menu = new GUI_frm_Menu();
        menu.setVisible(true);
        menu.menuTaiKhoan();
        
    }
    
    public void menuThongTin() {
        this.setVisible(false);
//        new GUI_dal_Loading(this, true).setVisible(true);
        GUI_frm_Menu menu = new GUI_frm_Menu();
        menu.setVisible(true);
        menu.menuThongTin();
    }
    
    public void dangXuat(){
        GUI_frm_DangNhap taiKhoan = new GUI_frm_DangNhap();
        this.setVisible(false);
        taiKhoan.setVisible(true);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTrangChu = new javax.swing.JPanel();
        pnlHinhAnh = new javax.swing.JPanel();
        lblHinhAnh = new javax.swing.JLabel();
        pnlTieuDe = new javax.swing.JPanel();
        lblTieuDe = new javax.swing.JLabel();
        pnlMenu = new javax.swing.JPanel();
        btnIconMonAn = new javax.swing.JButton();
        btnIconNhanVien = new javax.swing.JButton();
        btnIconThongTin = new javax.swing.JButton();
        btnIconDatban = new javax.swing.JButton();
        btnIconThongke = new javax.swing.JButton();
        lblMonAn = new javax.swing.JLabel();
        lblNhanVien = new javax.swing.JLabel();
        lblThongTin = new javax.swing.JLabel();
        lblDatBan = new javax.swing.JLabel();
        lblThongKe = new javax.swing.JLabel();
        btnIconTaiKhoan = new javax.swing.JButton();
        lblTaiKhoan = new javax.swing.JLabel();
        btnIconDangXuat = new javax.swing.JButton();
        lblDangXuat = new javax.swing.JLabel();
        btnIconThoat = new javax.swing.JButton();
        lblThoat_Menu = new javax.swing.JLabel();
        lblDanhSach = new javax.swing.JLabel();
        btnIconDanhSach = new javax.swing.JButton();
        btnIconHoaDon = new javax.swing.JButton();
        lblHoaDon = new javax.swing.JLabel();
        lblThoat_TrangChu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        pnlTrangChu.setBackground(new java.awt.Color(255, 255, 255));
        pnlTrangChu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlHinhAnh.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHinhAnh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/bg-360x550.jpg"))); // NOI18N
        pnlHinhAnh.add(lblHinhAnh, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 550));

        pnlTrangChu.add(pnlHinhAnh, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 550));

        pnlTieuDe.setBackground(new java.awt.Color(255, 255, 255));
        pnlTieuDe.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTieuDe.setBackground(new java.awt.Color(255, 255, 255));
        lblTieuDe.setFont(new java.awt.Font("Calibri Light", 1, 48)); // NOI18N
        lblTieuDe.setForeground(new java.awt.Color(49, 139, 130));
        lblTieuDe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTieuDe.setText("TRANG CHỦ");
        pnlTieuDe.add(lblTieuDe, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 590, 80));

        pnlTrangChu.add(pnlTieuDe, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, 610, 80));

        pnlMenu.setBackground(new java.awt.Color(255, 255, 255));
        pnlMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnIconMonAn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnIconMonAn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/hamburger_48px.png"))); // NOI18N
        btnIconMonAn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIconMonAnActionPerformed(evt);
            }
        });
        pnlMenu.add(btnIconMonAn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 116, 50));

        btnIconNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/staff_48px.png"))); // NOI18N
        btnIconNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIconNhanVienActionPerformed(evt);
            }
        });
        pnlMenu.add(btnIconNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 120, 50));

        btnIconThongTin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/info.png"))); // NOI18N
        btnIconThongTin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIconThongTinActionPerformed(evt);
            }
        });
        pnlMenu.add(btnIconThongTin, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 100, 50));

        btnIconDatban.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Checklist-icon.png"))); // NOI18N
        btnIconDatban.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIconDatbanActionPerformed(evt);
            }
        });
        pnlMenu.add(btnIconDatban, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, 100, 50));

        btnIconThongke.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/graph.png"))); // NOI18N
        btnIconThongke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIconThongkeActionPerformed(evt);
            }
        });
        pnlMenu.add(btnIconThongke, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 40, 99, 50));

        lblMonAn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblMonAn.setForeground(new java.awt.Color(49, 139, 130));
        lblMonAn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMonAn.setText("Món Ăn");
        pnlMenu.add(lblMonAn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 120, -1));

        lblNhanVien.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNhanVien.setForeground(new java.awt.Color(49, 139, 130));
        lblNhanVien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNhanVien.setText("Nhân Viên");
        pnlMenu.add(lblNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 120, -1));

        lblThongTin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblThongTin.setForeground(new java.awt.Color(49, 139, 130));
        lblThongTin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblThongTin.setText("Thông Tin");
        pnlMenu.add(lblThongTin, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 100, -1));

        lblDatBan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblDatBan.setForeground(new java.awt.Color(49, 139, 130));
        lblDatBan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDatBan.setText("Đặt Bàn");
        pnlMenu.add(lblDatBan, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, 100, -1));

        lblThongKe.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblThongKe.setForeground(new java.awt.Color(49, 139, 130));
        lblThongKe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblThongKe.setText("Thống Kê");
        pnlMenu.add(lblThongKe, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 100, 99, -1));

        btnIconTaiKhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/user-settings-icon.png"))); // NOI18N
        btnIconTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIconTaiKhoanActionPerformed(evt);
            }
        });
        pnlMenu.add(btnIconTaiKhoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 110, 50));

        lblTaiKhoan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTaiKhoan.setForeground(new java.awt.Color(49, 139, 130));
        lblTaiKhoan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTaiKhoan.setText("Tài Khoản");
        pnlMenu.add(lblTaiKhoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 110, -1));

        btnIconDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/logout_36px.png"))); // NOI18N
        btnIconDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIconDangXuatActionPerformed(evt);
            }
        });
        pnlMenu.add(btnIconDangXuat, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, 100, 50));

        lblDangXuat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblDangXuat.setForeground(new java.awt.Color(49, 139, 130));
        lblDangXuat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDangXuat.setText("Đăng Xuất");
        pnlMenu.add(lblDangXuat, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, 100, -1));

        btnIconThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/exit.png"))); // NOI18N
        btnIconThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIconThoatActionPerformed(evt);
            }
        });
        pnlMenu.add(btnIconThoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, 100, 50));

        lblThoat_Menu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblThoat_Menu.setForeground(new java.awt.Color(49, 139, 130));
        lblThoat_Menu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblThoat_Menu.setText("Thoát");
        lblThoat_Menu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlMenu.add(lblThoat_Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 210, 100, -1));

        lblDanhSach.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblDanhSach.setForeground(new java.awt.Color(49, 139, 130));
        lblDanhSach.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDanhSach.setText("Danh Sách");
        pnlMenu.add(lblDanhSach, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 110, -1));

        btnIconDanhSach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/coffee-table.png"))); // NOI18N
        btnIconDanhSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIconDanhSachActionPerformed(evt);
            }
        });
        pnlMenu.add(btnIconDanhSach, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 110, 50));

        btnIconHoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/billing_machine_60px.png"))); // NOI18N
        btnIconHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIconHoaDonActionPerformed(evt);
            }
        });
        pnlMenu.add(btnIconHoaDon, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 100, 50));

        lblHoaDon.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblHoaDon.setForeground(new java.awt.Color(49, 139, 130));
        lblHoaDon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHoaDon.setText("Hóa Ðơn");
        pnlMenu.add(lblHoaDon, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 100, -1));

        pnlTrangChu.add(pnlMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, 670, 270));

        lblThoat_TrangChu.setBackground(new java.awt.Color(49, 139, 130));
        lblThoat_TrangChu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Close_18px.png"))); // NOI18N
        lblThoat_TrangChu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblThoat_TrangChuMouseClicked(evt);
            }
        });
        pnlTrangChu.add(lblThoat_TrangChu, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 10, 20, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pnlTrangChu, javax.swing.GroupLayout.PREFERRED_SIZE, 1070, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pnlTrangChu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIconMonAnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIconMonAnActionPerformed
        menuMonAn();
    }//GEN-LAST:event_btnIconMonAnActionPerformed

    private void btnIconNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIconNhanVienActionPerformed
        menuNhanVien();
    }//GEN-LAST:event_btnIconNhanVienActionPerformed

    private void btnIconThongTinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIconThongTinActionPerformed
        menuThongTin();
    }//GEN-LAST:event_btnIconThongTinActionPerformed

    private void btnIconDatbanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIconDatbanActionPerformed
        menuDatBan();
    }//GEN-LAST:event_btnIconDatbanActionPerformed

    private void btnIconThongkeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIconThongkeActionPerformed
        menuThongKe();
    }//GEN-LAST:event_btnIconThongkeActionPerformed

    private void btnIconTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIconTaiKhoanActionPerformed
        menuTaiKhoan();
    }//GEN-LAST:event_btnIconTaiKhoanActionPerformed

    private void btnIconDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIconDangXuatActionPerformed
        dangXuat();
    }//GEN-LAST:event_btnIconDangXuatActionPerformed

    private void btnIconThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIconThoatActionPerformed
        thoat();
    }//GEN-LAST:event_btnIconThoatActionPerformed

    private void btnIconDanhSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIconDanhSachActionPerformed
        menuDanhSach();
    }//GEN-LAST:event_btnIconDanhSachActionPerformed

    private void btnIconHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIconHoaDonActionPerformed
        menuHoaDon();
    }//GEN-LAST:event_btnIconHoaDonActionPerformed

    private void lblThoat_TrangChuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThoat_TrangChuMouseClicked
        thoat();
    }//GEN-LAST:event_lblThoat_TrangChuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_frm_TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_frm_TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_frm_TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_frm_TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_frm_TrangChu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIconDangXuat;
    private javax.swing.JButton btnIconDanhSach;
    private javax.swing.JButton btnIconDatban;
    private javax.swing.JButton btnIconHoaDon;
    private javax.swing.JButton btnIconMonAn;
    private javax.swing.JButton btnIconNhanVien;
    private javax.swing.JButton btnIconTaiKhoan;
    private javax.swing.JButton btnIconThoat;
    private javax.swing.JButton btnIconThongTin;
    private javax.swing.JButton btnIconThongke;
    private javax.swing.JLabel lblDangXuat;
    private javax.swing.JLabel lblDanhSach;
    private javax.swing.JLabel lblDatBan;
    private javax.swing.JLabel lblHinhAnh;
    private javax.swing.JLabel lblHoaDon;
    private javax.swing.JLabel lblMonAn;
    private javax.swing.JLabel lblNhanVien;
    private javax.swing.JLabel lblTaiKhoan;
    private javax.swing.JLabel lblThoat_Menu;
    private javax.swing.JLabel lblThoat_TrangChu;
    private javax.swing.JLabel lblThongKe;
    private javax.swing.JLabel lblThongTin;
    private javax.swing.JLabel lblTieuDe;
    private javax.swing.JPanel pnlHinhAnh;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlTieuDe;
    private javax.swing.JPanel pnlTrangChu;
    // End of variables declaration//GEN-END:variables
}
