/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import BLL.BLL_TaiKhoan;
import DAL.DAL_TaiKhoan;
import DTO.DTO_TaiKhoan;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author CherryCe
 */
public class GUI_frm_DangKi extends javax.swing.JFrame {

    boolean isPassword = false;

    /**
     * Creates new form frm_TaiKhoan
     */
    public GUI_frm_DangKi() {
        initComponents();
        setLocationRelativeTo(null);
    }

    public void signUp() {
        DTO_TaiKhoan dto_taiKhoan = new DTO_TaiKhoan(txtMaNhanVien.getText(), txtTaiKhoan.getText(), String.valueOf(txtMatKhau.getPassword()), String.valueOf(cboPhanQuyen.getSelectedItem()));
        BLL_TaiKhoan.add(dto_taiKhoan);
        JOptionPane.showMessageDialog(this, "Complete");
        this.setVisible(false);
        new GUI_frm_DangNhap().setVisible(true);

    }

    public void exit() {
        int choice = JOptionPane.showConfirmDialog(this, "Bạn Có Muốn Thoát Chương Trình ?", "Thoát", JOptionPane.YES_NO_OPTION);
        if (choice == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
        return;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHinhAnh = new javax.swing.JLabel();
        lblTaiKhoan = new javax.swing.JLabel();
        lblKiemTraTaiKhoan = new javax.swing.JLabel();
        pnlDangKi = new javax.swing.JPanel();
        lblIconMaNhanVien = new javax.swing.JLabel();
        lblIconMatKhau = new javax.swing.JLabel();
        btnDangKi = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        txtMaNhanVien = new javax.swing.JTextField();
        lblDangKi = new javax.swing.JLabel();
        txtMatKhau = new javax.swing.JPasswordField();
        lblThoat = new javax.swing.JLabel();
        cboPhanQuyen = new javax.swing.JComboBox<>();
        lblIconTaiKhoan = new javax.swing.JLabel();
        txtTaiKhoan = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(654, 410));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(654, 410));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHinhAnh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/bg-306x410.jpg"))); // NOI18N
        getContentPane().add(lblHinhAnh, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 304, -1));

        lblTaiKhoan.setBackground(new java.awt.Color(255, 255, 255));
        lblTaiKhoan.setText("ĐĂNG NHẬP");
        lblTaiKhoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTaiKhoanMouseClicked(evt);
            }
        });
        getContentPane().add(lblTaiKhoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 380, -1, 30));

        lblKiemTraTaiKhoan.setText("Bạn Đã Có Tài Khoản ?");
        getContentPane().add(lblKiemTraTaiKhoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 380, -1, 30));

        pnlDangKi.setBackground(new java.awt.Color(255, 255, 255));
        pnlDangKi.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIconMaNhanVien.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblIconMaNhanVien.setForeground(new java.awt.Color(49, 139, 130));
        lblIconMaNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/icons8-face-id-28.png"))); // NOI18N
        lblIconMaNhanVien.setToolTipText("");
        pnlDangKi.add(lblIconMaNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        lblIconMatKhau.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblIconMatKhau.setForeground(new java.awt.Color(49, 139, 130));
        lblIconMatKhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/password_28px.png"))); // NOI18N
        pnlDangKi.add(lblIconMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 26, 22));

        btnDangKi.setBackground(new java.awt.Color(49, 139, 130));
        btnDangKi.setText("Đăng Kí");
        btnDangKi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDangKiMouseClicked(evt);
            }
        });
        btnDangKi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangKiActionPerformed(evt);
            }
        });
        pnlDangKi.add(btnDangKi, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 298, -1, 35));

        btnThoat.setBackground(new java.awt.Color(49, 139, 130));
        btnThoat.setText("Thoát");
        btnThoat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThoatMouseClicked(evt);
            }
        });
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });
        pnlDangKi.add(btnThoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 298, 88, 35));

        txtMaNhanVien.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        pnlDangKi.add(txtMaNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 214, -1));

        lblDangKi.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblDangKi.setForeground(new java.awt.Color(49, 139, 130));
        lblDangKi.setText("ĐĂNG KÍ");
        pnlDangKi.add(lblDangKi, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 57, -1, 54));

        txtMatKhau.setFocusAccelerator('\u0001');
        txtMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMatKhauActionPerformed(evt);
            }
        });
        pnlDangKi.add(txtMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 214, -1));

        lblThoat.setBackground(new java.awt.Color(49, 139, 130));
        lblThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Close_18px.png"))); // NOI18N
        lblThoat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblThoatMouseClicked(evt);
            }
        });
        pnlDangKi.add(lblThoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, -1, -1));

        cboPhanQuyen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Quản Lý", "Nhân Viên" }));
        cboPhanQuyen.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlDangKi.add(cboPhanQuyen, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 248, 214, -1));

        lblIconTaiKhoan.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblIconTaiKhoan.setForeground(new java.awt.Color(49, 139, 130));
        lblIconTaiKhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/accountt_28px.png"))); // NOI18N
        lblIconTaiKhoan.setToolTipText("");
        pnlDangKi.add(lblIconTaiKhoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        txtTaiKhoan.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        pnlDangKi.add(txtTaiKhoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 214, -1));

        getContentPane().add(pnlDangKi, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, -1, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblTaiKhoanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTaiKhoanMouseClicked
        this.setVisible(false);
        new GUI_frm_DangNhap().setVisible(true);
    }//GEN-LAST:event_lblTaiKhoanMouseClicked

    private void btnDangKiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDangKiMouseClicked
        signUp();
    }//GEN-LAST:event_btnDangKiMouseClicked

    private void btnDangKiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangKiActionPerformed

    }//GEN-LAST:event_btnDangKiActionPerformed

    private void btnThoatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThoatMouseClicked
        exit();
    }//GEN-LAST:event_btnThoatMouseClicked

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed

    }//GEN-LAST:event_btnThoatActionPerformed

    private void txtMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMatKhauActionPerformed

    }//GEN-LAST:event_txtMatKhauActionPerformed

    private void lblThoatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThoatMouseClicked
        exit();
    }//GEN-LAST:event_lblThoatMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_frm_DangKi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_frm_DangKi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_frm_DangKi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_frm_DangKi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_frm_DangKi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangKi;
    private javax.swing.JButton btnThoat;
    private javax.swing.JComboBox<String> cboPhanQuyen;
    private javax.swing.JLabel lblDangKi;
    private javax.swing.JLabel lblHinhAnh;
    private javax.swing.JLabel lblIconMaNhanVien;
    private javax.swing.JLabel lblIconMatKhau;
    private javax.swing.JLabel lblIconTaiKhoan;
    public javax.swing.JLabel lblKiemTraTaiKhoan;
    public javax.swing.JLabel lblTaiKhoan;
    private javax.swing.JLabel lblThoat;
    private javax.swing.JPanel pnlDangKi;
    private javax.swing.JTextField txtMaNhanVien;
    private javax.swing.JPasswordField txtMatKhau;
    private javax.swing.JTextField txtTaiKhoan;
    // End of variables declaration//GEN-END:variables
}
