/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import BLL.BLL_HoaDon;
import DTO.DTO_HoaDon;
import HELPER.HELPER_ChuyenDoi;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author CherryCe
 */
public class GUI_pnl_ThongKe extends javax.swing.JPanel {

    /**
     * Creates new form pnl_ThongKe
     */
    public GUI_pnl_ThongKe() {
        initComponents();
        load();
    }

    public void setSTT() {
        for (int i = 0; i < tblThongKe.getRowCount(); i++) {
            tblThongKe.setValueAt(i + 1, i, 0);
        }
    }

    public void load() {
        ArrayList<DTO_HoaDon> arrayHoaDon = BLL_HoaDon.select();
        BLL_HoaDon.load(arrayHoaDon, tblThongKe);
        double tongTien = 0;
        for (int i = 0; i < tblThongKe.getRowCount(); i++) {
            tongTien += HELPER_ChuyenDoi.SoDouble(tblThongKe.getValueAt(i, 5).toString());
            tblThongKe.setValueAt(i + 1, i, 0);
        }
        lblSetSoLuong.setText(HELPER_ChuyenDoi.SoString(tblThongKe.getRowCount()));
        lblSetTongTien.setText(HELPER_ChuyenDoi.SoString(tongTien));
    }

    public void findDate() {
        ArrayList<DTO_HoaDon> arrayHoaDon = BLL_HoaDon.findDate(HELPER_ChuyenDoi.LayNgayString(dateThoiGian.getDate()));
        BLL_HoaDon.load(arrayHoaDon, tblThongKe);
    }

    public void thoat() {
        int choice = JOptionPane.showConfirmDialog(this, "Bạn có muốn thoát chương trình ?", "Thoát", JOptionPane.YES_NO_OPTION);
        if (choice == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
        return;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlThongKe = new javax.swing.JPanel();
        lblThoat = new javax.swing.JLabel();
        scrThongKe = new javax.swing.JScrollPane();
        tblThongKe = new javax.swing.JTable();
        pnlFormChinh = new javax.swing.JPanel();
        btnTraCuu = new javax.swing.JButton();
        btnTroLai = new javax.swing.JButton();
        dateThoiGian = new com.toedter.calendar.JDateChooser();
        lblThoiGian = new javax.swing.JLabel();
        lblTieuDe = new javax.swing.JLabel();
        cboThoiGian = new javax.swing.JComboBox<>();
        pnlTongHoaDon = new javax.swing.JPanel();
        lblSetTongTien = new javax.swing.JLabel();
        lblTongSo = new javax.swing.JLabel();
        lblTongTien = new javax.swing.JLabel();
        lblSetSoLuong = new javax.swing.JLabel();

        pnlThongKe.setBackground(new java.awt.Color(255, 255, 255));
        pnlThongKe.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblThoat.setBackground(new java.awt.Color(49, 139, 130));
        lblThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Close_18px.png"))); // NOI18N
        lblThoat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblThoatMouseClicked(evt);
            }
        });
        pnlThongKe.add(lblThoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 10, 20, 20));

        tblThongKe.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tblThongKe.setForeground(new java.awt.Color(49, 139, 130));
        tblThongKe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã Hóa Đơn", "Tên Bàn", "Nhân Viên", "Ngày Bán", "Tổng Tiền Hóa Ðơn"
            }
        ));
        tblThongKe.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblThongKe.setGridColor(new java.awt.Color(0, 102, 102));
        tblThongKe.setSelectionBackground(new java.awt.Color(109, 182, 179));
        scrThongKe.setViewportView(tblThongKe);

        pnlThongKe.add(scrThongKe, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 900, 370));

        pnlFormChinh.setBackground(new java.awt.Color(255, 255, 255));
        pnlFormChinh.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnTraCuu.setBackground(new java.awt.Color(255, 255, 255));
        btnTraCuu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnTraCuu.setForeground(new java.awt.Color(49, 139, 130));
        btnTraCuu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/search_28px.png"))); // NOI18N
        btnTraCuu.setText("Tra Cứu");
        btnTraCuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTraCuuActionPerformed(evt);
            }
        });
        pnlFormChinh.add(btnTraCuu, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 120, 130, 30));

        btnTroLai.setBackground(new java.awt.Color(255, 255, 255));
        btnTroLai.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnTroLai.setForeground(new java.awt.Color(49, 139, 130));
        btnTroLai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/reset_28px.png"))); // NOI18N
        btnTroLai.setText("Trở Lại");
        btnTroLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTroLaiActionPerformed(evt);
            }
        });
        pnlFormChinh.add(btnTroLai, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 120, 126, 30));

        dateThoiGian.setDateFormatString("yyyy-MM-dd");
        pnlFormChinh.add(dateThoiGian, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 230, 30));

        lblThoiGian.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblThoiGian.setForeground(new java.awt.Color(49, 139, 130));
        lblThoiGian.setText("Thời Gian :");
        pnlFormChinh.add(lblThoiGian, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, 30));

        lblTieuDe.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        lblTieuDe.setForeground(new java.awt.Color(49, 139, 130));
        lblTieuDe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTieuDe.setText("Thống Kê");
        lblTieuDe.setToolTipText("");
        pnlFormChinh.add(lblTieuDe, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 290, -1));

        cboThoiGian.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cboThoiGian.setForeground(new java.awt.Color(49, 139, 130));
        cboThoiGian.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Giờ Vừa Qua", "Ngày Vừa Qua", "Tuần Vừa Qua" }));
        cboThoiGian.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboThoiGianItemStateChanged(evt);
            }
        });
        pnlFormChinh.add(cboThoiGian, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 120, 200, 30));

        pnlThongKe.add(pnlFormChinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 900, 160));

        pnlTongHoaDon.setBackground(new java.awt.Color(255, 255, 255));

        lblSetTongTien.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSetTongTien.setForeground(new java.awt.Color(49, 139, 130));

        lblTongSo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTongSo.setForeground(new java.awt.Color(49, 139, 130));
        lblTongSo.setText("Tổng Số Hóa Ðơn:");

        lblTongTien.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTongTien.setForeground(new java.awt.Color(49, 139, 130));
        lblTongTien.setText("Tổng Tiền Hóa Ðơn:");

        lblSetSoLuong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSetSoLuong.setForeground(new java.awt.Color(49, 139, 130));

        javax.swing.GroupLayout pnlTongHoaDonLayout = new javax.swing.GroupLayout(pnlTongHoaDon);
        pnlTongHoaDon.setLayout(pnlTongHoaDonLayout);
        pnlTongHoaDonLayout.setHorizontalGroup(
            pnlTongHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTongHoaDonLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(lblTongSo, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblSetSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 180, Short.MAX_VALUE)
                .addComponent(lblTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSetTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        pnlTongHoaDonLayout.setVerticalGroup(
            pnlTongHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTongHoaDonLayout.createSequentialGroup()
                .addGroup(pnlTongHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlTongHoaDonLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblSetSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlTongHoaDonLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(pnlTongHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTongSo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSetTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(4, 4, 4))
        );

        pnlThongKe.add(pnlTongHoaDon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 570, 900, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 920, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 920, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lblThoatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThoatMouseClicked
        thoat();
    }//GEN-LAST:event_lblThoatMouseClicked

    private void btnTraCuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTraCuuActionPerformed
        if (dateThoiGian.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Dữ Liệu Không Được Để Trống ???");
            return;
        } else {
            findDate();
            setSTT();
        }
    }//GEN-LAST:event_btnTraCuuActionPerformed

    private void btnTroLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTroLaiActionPerformed
        ArrayList<DTO_HoaDon> arrayHoaDon = BLL_HoaDon.select();
        BLL_HoaDon.load(arrayHoaDon, tblThongKe);
        setSTT();
    }//GEN-LAST:event_btnTroLaiActionPerformed

    private void cboThoiGianItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboThoiGianItemStateChanged
        setSTT();
    }//GEN-LAST:event_cboThoiGianItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTraCuu;
    private javax.swing.JButton btnTroLai;
    private javax.swing.JComboBox<String> cboThoiGian;
    private com.toedter.calendar.JDateChooser dateThoiGian;
    private javax.swing.JLabel lblSetSoLuong;
    private javax.swing.JLabel lblSetTongTien;
    private javax.swing.JLabel lblThoat;
    private javax.swing.JLabel lblThoiGian;
    private javax.swing.JLabel lblTieuDe;
    private javax.swing.JLabel lblTongSo;
    private javax.swing.JLabel lblTongTien;
    private javax.swing.JPanel pnlFormChinh;
    private javax.swing.JPanel pnlThongKe;
    private javax.swing.JPanel pnlTongHoaDon;
    private javax.swing.JScrollPane scrThongKe;
    private javax.swing.JTable tblThongKe;
    // End of variables declaration//GEN-END:variables
}
