/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import BLL.BLL_DanhSach;
import BLL.BLL_MaTenLoai;
import BLL.BLL_NhanVien;
import DTO.DTO_DanhSach;
import DTO.DTO_NhanVien;
import HELPER.HELPER_ChuyenDoi;
import HELPER.HELPER_ShowHinhAnh;
import java.util.ArrayList;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.JTextField;

/**
 *
 * @author CherryCe
 */
public class GUI_pnl_DanhSach extends javax.swing.JPanel {

    String Url;
    int index = -1;

    /**
     * Creates new form pnl_DanhSach
     */
    public GUI_pnl_DanhSach() {
        initComponents();
        load();
        btnThem.setEnabled(false);
        btnXoa.setEnabled(false);
    }

    public void add() {
        String trangThai = null;
        if (rdoCoKhach.isSelected()) {
            trangThai = "Có Khách";
        } else if (rdoKhachDat.isSelected()) {
            trangThai = "Khách Đặt";
        } else if (rdoBanTrong.isSelected()) {
            trangThai = "Bàn Trống";
        }
        DTO_DanhSach danhSach = new DTO_DanhSach(txtMaBan.getText(), txtTenBan.getText(), trangThai);
        BLL_DanhSach.add(danhSach);
    }

    public void delete(int index) {
        String trangThai = null;
        if (rdoCoKhach.isSelected()) {
            trangThai = "Có Khách";
        } else if (rdoKhachDat.isSelected()) {
            trangThai = "Khách Đặt";
        } else if (rdoBanTrong.isSelected()) {
            trangThai = "Bàn Trống";
        }
        if (index < 0) {
            JOptionPane.showMessageDialog(this, "Bạn Chưa Chọn Dòng Cần Sửa");
        } else {
            int choice = JOptionPane.showConfirmDialog(this, "Bạn Có Muốn Xóa Không ?", "Xóa", JOptionPane.YES_NO_OPTION);
            if (choice == JOptionPane.YES_OPTION) {
                int indexs[] = tblDanhSach.getSelectedRows();
                for (int i = 0; i < indexs.length; i++) {
                    String maBan = tblDanhSach.getValueAt(indexs[i], 0).toString();
                    BLL_DanhSach.delete(maBan);
                }
                DTO_DanhSach danhSach = new DTO_DanhSach(txtMaBan.getText(), txtTenBan.getText(), trangThai);
            }
            return;
        }
    }

    public void edit(int index) {
        String trangThai = null;
        if (rdoCoKhach.isSelected()) {
            trangThai = "Có Khách";
        } else if (rdoKhachDat.isSelected()) {
            trangThai = "Khách Đặt";
        } else if (rdoBanTrong.isSelected()) {
            trangThai = "Bàn Trống";
        }
        if (index < 0) {
            JOptionPane.showMessageDialog(this, "Bạn Chưa Chọn Dòng Cần Sửa");
        }
        DTO_DanhSach danhSach = new DTO_DanhSach(txtMaBan.getText(), txtTenBan.getText(), trangThai);
        BLL_DanhSach.edit(danhSach);
    }

    public void reset() {
        txtMaBan.setText(null);
        txtTenBan.setText(null);
        rdoBanTrong.setSelected(true);
    }

    public void fill(int index) {
        txtMaBan.setText(tblDanhSach.getValueAt(index, 0).toString());
        txtTenBan.setText(tblDanhSach.getValueAt(index, 1).toString());
        String trangThai = tblDanhSach.getValueAt(index, 2).toString();
        if (trangThai.equals("Có Khách")) {
            rdoCoKhach.setSelected(true);
        } else if (trangThai.equals("Khách Đặt")) {
            rdoKhachDat.setSelected(true);
        } else if (trangThai.equals("Bàn Trống")) {
            rdoBanTrong.setSelected(true);
        }
    }

    public void load() {
        ArrayList<DTO_DanhSach> array = BLL_DanhSach.select();
        BLL_DanhSach.load(array, tblDanhSach);
        rdoBanTrong.setSelected(true);
    }

    public void exit() {
        int choice = JOptionPane.showConfirmDialog(this, "Bạn Có Muốn Thoát Chương Trình ?", "Thoát", JOptionPane.YES_NO_OPTION);
        if (choice == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
        return;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grpTrangThai = new javax.swing.ButtonGroup();
        pnlDanhSach = new javax.swing.JPanel();
        lblThoat = new javax.swing.JLabel();
        scrDanhSach = new javax.swing.JScrollPane();
        tblDanhSach = new javax.swing.JTable();
        pnlFormChinh = new javax.swing.JPanel();
        lblTenBan = new javax.swing.JLabel();
        lblMaBan = new javax.swing.JLabel();
        lblTrangThai = new javax.swing.JLabel();
        txtMaBan = new javax.swing.JTextField();
        txtTenBan = new javax.swing.JTextField();
        rdoBanTrong = new javax.swing.JRadioButton();
        rdoCoKhach = new javax.swing.JRadioButton();
        btnLamMoi = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        rdoKhachDat = new javax.swing.JRadioButton();
        lblThongTin = new javax.swing.JLabel();
        pnlTieuDe = new javax.swing.JPanel();
        lblDanhSach = new javax.swing.JLabel();

        pnlDanhSach.setBackground(new java.awt.Color(255, 255, 255));
        pnlDanhSach.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblThoat.setBackground(new java.awt.Color(49, 139, 130));
        lblThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Close_18px.png"))); // NOI18N
        lblThoat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblThoatMouseClicked(evt);
            }
        });
        pnlDanhSach.add(lblThoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 10, 20, 20));

        tblDanhSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã Bàn", "Tên Bàn", "Trạng Thái"
            }
        ));
        tblDanhSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDanhSachMouseClicked(evt);
            }
        });
        scrDanhSach.setViewportView(tblDanhSach);

        pnlDanhSach.add(scrDanhSach, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 127, 560, 480));

        pnlFormChinh.setBackground(new java.awt.Color(255, 255, 255));

        lblTenBan.setForeground(new java.awt.Color(49, 139, 130));
        lblTenBan.setText("Tên Bàn:");

        lblMaBan.setForeground(new java.awt.Color(49, 139, 130));
        lblMaBan.setText("Mã Bàn:");

        lblTrangThai.setForeground(new java.awt.Color(49, 139, 130));
        lblTrangThai.setText("Trạng Thái:");

        txtMaBan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMaBanKeyReleased(evt);
            }
        });

        rdoBanTrong.setBackground(new java.awt.Color(255, 255, 255));
        grpTrangThai.add(rdoBanTrong);
        rdoBanTrong.setForeground(new java.awt.Color(49, 139, 130));
        rdoBanTrong.setText("Bàn Trống");

        rdoCoKhach.setBackground(new java.awt.Color(255, 255, 255));
        grpTrangThai.add(rdoCoKhach);
        rdoCoKhach.setForeground(new java.awt.Color(49, 139, 130));
        rdoCoKhach.setText("Có Khách");

        btnLamMoi.setForeground(new java.awt.Color(49, 139, 130));
        btnLamMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/reset_28px.png"))); // NOI18N
        btnLamMoi.setText("Làm Mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        btnXoa.setForeground(new java.awt.Color(49, 139, 130));
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Delete_28px.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnSua.setForeground(new java.awt.Color(49, 139, 130));
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/edit_28px.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.setToolTipText("");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnThem.setForeground(new java.awt.Color(49, 139, 130));
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/add_28px.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        rdoKhachDat.setBackground(new java.awt.Color(255, 255, 255));
        grpTrangThai.add(rdoKhachDat);
        rdoKhachDat.setForeground(new java.awt.Color(49, 139, 130));
        rdoKhachDat.setText("Khách Ðặt");

        lblThongTin.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblThongTin.setForeground(new java.awt.Color(49, 139, 130));
        lblThongTin.setText("Thông Tin:");
        lblThongTin.setToolTipText("");

        javax.swing.GroupLayout pnlFormChinhLayout = new javax.swing.GroupLayout(pnlFormChinh);
        pnlFormChinh.setLayout(pnlFormChinhLayout);
        pnlFormChinhLayout.setHorizontalGroup(
            pnlFormChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFormChinhLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(pnlFormChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblThongTin)
                    .addGroup(pnlFormChinhLayout.createSequentialGroup()
                        .addGroup(pnlFormChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addGroup(pnlFormChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnThem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlFormChinhLayout.createSequentialGroup()
                        .addGroup(pnlFormChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblTrangThai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblMaBan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTenBan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlFormChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlFormChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(rdoBanTrong)
                                .addComponent(txtMaBan, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                                .addComponent(txtTenBan))
                            .addComponent(rdoKhachDat)
                            .addComponent(rdoCoKhach))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        pnlFormChinhLayout.setVerticalGroup(
            pnlFormChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFormChinhLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblThongTin, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(pnlFormChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaBan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMaBan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlFormChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTenBan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTenBan, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(pnlFormChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdoBanTrong))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdoCoKhach)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdoKhachDat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(pnlFormChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLamMoi)
                    .addComponent(btnThem))
                .addGap(36, 36, 36)
                .addGroup(pnlFormChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSua)
                    .addComponent(btnXoa))
                .addGap(66, 66, 66))
        );

        pnlDanhSach.add(pnlFormChinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 120, 340, 480));

        pnlTieuDe.setBackground(new java.awt.Color(255, 255, 255));

        lblDanhSach.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lblDanhSach.setForeground(new java.awt.Color(49, 139, 130));
        lblDanhSach.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDanhSach.setText("QUẢN LÝ DANH SÁCH");

        javax.swing.GroupLayout pnlTieuDeLayout = new javax.swing.GroupLayout(pnlTieuDe);
        pnlTieuDe.setLayout(pnlTieuDeLayout);
        pnlTieuDeLayout.setHorizontalGroup(
            pnlTieuDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTieuDeLayout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(lblDanhSach, javax.swing.GroupLayout.PREFERRED_SIZE, 848, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        pnlTieuDeLayout.setVerticalGroup(
            pnlTieuDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTieuDeLayout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(lblDanhSach)
                .addGap(14, 14, 14))
        );

        pnlDanhSach.add(pnlTieuDe, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 110));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 920, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlDanhSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlDanhSach, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lblThoatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThoatMouseClicked
        exit();
    }//GEN-LAST:event_lblThoatMouseClicked

    private void tblDanhSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDanhSachMouseClicked
        index = tblDanhSach.getSelectedRow();
        fill(index);
    }//GEN-LAST:event_tblDanhSachMouseClicked

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        reset();
        load();
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        index = tblDanhSach.getSelectedRow();

        delete(index);
        reset();
        load();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        index = tblDanhSach.getSelectedRow();

        edit(index);
        load();
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        add();
        load();
    }//GEN-LAST:event_btnThemActionPerformed

    private void txtMaBanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMaBanKeyReleased
        BLL_MaTenLoai.isAdd(tblDanhSach, txtMaBan, btnThem, 0);
    }//GEN-LAST:event_txtMaBanKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.ButtonGroup grpTrangThai;
    private javax.swing.JLabel lblDanhSach;
    private javax.swing.JLabel lblMaBan;
    private javax.swing.JLabel lblTenBan;
    private javax.swing.JLabel lblThoat;
    private javax.swing.JLabel lblThongTin;
    private javax.swing.JLabel lblTrangThai;
    private javax.swing.JPanel pnlDanhSach;
    private javax.swing.JPanel pnlFormChinh;
    private javax.swing.JPanel pnlTieuDe;
    private javax.swing.JRadioButton rdoBanTrong;
    private javax.swing.JRadioButton rdoCoKhach;
    private javax.swing.JRadioButton rdoKhachDat;
    private javax.swing.JScrollPane scrDanhSach;
    private javax.swing.JTable tblDanhSach;
    private javax.swing.JTextField txtMaBan;
    private javax.swing.JTextField txtTenBan;
    // End of variables declaration//GEN-END:variables
}
